### ISSUE TITLE
Add Allele Origin and Collection Method data to GraphQL SCV results

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-streams#11]
Acceptance Criteria:

An API user can perform a GraphQL query for SCV data:

SCV Field List
Collection Method*

Allele Origin*

*Need to unpack these fields - defer to separate ticket if needed

**Comment by theferrit32** [comment]
In progress

**Comment by theferrit32** [comment]
Added to upstream combiner service. Parses and converts all allele origin and collection method values to an array on the observation sub-object of the assertions. Have not updated genegraph to aggregate as part of graphql response

**Comment by theferrit32** [comment]
Resolved in https://github.com/clingen-data-model/clinvar-streams/commit/3251b24a7c581d64fc06177db3946f1445e8a3ac
