### ISSUE TITLE
Enhance pipeline to auto-classify into Classification Context bins defined by ClinGen

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-streams#12]
[ClinGenVar Requirements Doc](https://docs.google.com/document/d/1Npxnwi2J85qE9nMry8jdeOV1H-wVMLHaMc12HUdXN78/edit?usp=sharing)
Larry to clean up specification prior to passing to @theferrit32  to implement

**Comment by theferrit32** [comment]
@larrybabb this should probably be closed and tracked in `genegraph` instead:

https://github.com/clingen-data-model/genegraph/issues/134
