### ISSUE TITLE
Move clinvar-combiner sql from inline code to separate files in subdirectory

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-streams#16]
Create files in `src/clinvar_streams/storage/database_sqlite/sql/sink/`

Some will be pure executable sql, some will contain preparedstatement `?` symbols, some will need to have string substitution symbols (like `{{in-clause}}`).

This is for readability of both the sql and the clojure code in `sink.clj`.

**Comment by larrybabb** [comment]
always a good idea to refactor code to be better organized. I'm closing this ticket since it's been archived for so long. We can re-open or create a new ticket if it is worthwhile.
