### ISSUE TITLE
Investigate connection from Confluent to AWS Lambda

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-streams#18]
AWS Lambda's kafka source config is limited to SCRAM authentication method. 

Investigate whether Confluent managed clusters can support SCRAM. If not, investigate alternate method for connecting a Confluent cluster to an AWS Lambda sink (intermediary kafka consumer container that async invokes lambda function).

---

Kyle F. - Feb 26, 2021
This is based on a request from Rao, but may be useful for other users wanting to ingest kafka streams through lambda or gcp cloud functions. Confluent has a connector for both AWS Lambda and GCP Cloud Functions, but this would take administration of the connection away from users, as we would need to add a config item for each user who wants the messages. We would also have to administer offset resetting for them.

**Comment by tnavatar** [comment]
https://docs.confluent.io/cloud/current/connectors/cc-aws-lambda-sink.html <https://docs.confluent.io/cloud/current/connectors/cc-aws-lambda-sink.html> ?

**Comment by larrybabb** [comment]
@theferrit32 no immediate action needed unless you tell me that this is a priority for Stanford (Rao). Otherwise let's let this percolate until there is a greater demand.

**Comment by larrybabb** [comment]
closing this. outdated. Rao is no longer at Stanford and I'm confident that Karen Dalton is not actively planning on this work. If it comes back in the future we will open a new ticket to assist Stanford with this plan.
