### ISSUE TITLE
Implement deeper schema checks on combiner output messages

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-streams#24]
There are a few sanity checks in place to make sure *obviously* non-nullable fields are not empty in the output message, but there should be more validation.

Some of this should be actual value based in the building of the clinical assertion. Such as an empty resultset for a query that was expected to return at least one result.

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Closed - Combiner is being removed from architecture with new GG transformer mode
