### ISSUE TITLE
Remove 'empty' values from output combiner messages

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-streams#25]
This will lessen some downstream processing burden and reduce message sizes slightly. When ingesting all fields into a graph database, this will also reduce the number of triples.

- null
- empty string
- empty array
- empty json array (serialized as json string)
- empty object

Should work recursively on both object/maps and arrays elements:

https://github.com/clingen-data-model/clinvar-api/blob/c7064e930fbb143e121bf29c344c6c016bb0f4d9/clinvar_api/clinvar_api/generate.py#L88-L106

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Closed
