### ISSUE TITLE
Remove combiner metadata fields from output clinical_assertions and set release_date to latest

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-streams#4]
- dirty on top and nested objects
- event_type on top and nested objects
- release_date on nested objects (set top level release_date to max of all release_dates)

**Comment by larrybabb** [comment]
@theferrit32 any updates on the current status or plan would be appreciated.

**Comment by theferrit32** [comment]
This should be prioritized next for more accurate review of output data particularly because release_date is now being used downstream for determining the latest view of data.

**Comment by theferrit32** [comment]
I'm prioritizing this as part of the updates from https://github.com/clingen-data-model/clinvar-streams/issues/17

Might as well make all these changes at the same time
