### ISSUE TITLE
Modify ClinVar DX Topics to be Entity-Based

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-streams#51]
After discussion with Kyle, It seems like it would be potentially better for consumers to have topics based on entities (VCV, RCV, SCV, Variation, Disease, Submitter, Submission, Gene). This would provide a clean separation on the topics and allow for us to use topic schemas to validate the content.

**Comment by KelseaChang5** [comment]
Will revisit if the need arises
